## Setup

In [ ]:
# Cell 1: Install và import thư viện
%conda install fastai torch torchvision pycocotools scikit-learn cpuonly -q

## Classification

In [10]:
from fastai.vision.all import *

In [11]:
set_seed(42, reproducible=True)
path = untar_data(URLs.PETS)/'images'
dls = ImageDataLoaders.from_name_func(
    path, get_image_files(path), valid_pct=0.2,
    label_func=lambda x: x[0].isupper(), item_tfms=Resize(224))

In [ ]:
learn = vision_learner(dls, resnet18, pretrained=True, metrics=error_rate)
learn.fine_tune(3)

In [ ]:
img = PILImage.create('../images/bo du lieu bia so 4/bia4 (1).bmp')
pred, pred_idx, probs = learn.predict(img)
print(f'Prediction: {pred}; Probability: {probs[pred_idx]:.04f}')